apiVersion: fn.kpt.dev/v1alpha1
kind: EnsureNameSubstring
metadata:
  name: foo-foobar
  annotations:
    config.kubernetes.io/local-config: "true"
substring: "foo-"
editMode: prepend
additionalNameFields:
- kind: SomeCR
  path: spec/foo/bar
