apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: wildcard
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  name: "*.example.com."
  type: "A"
  ttl: 3600
  managedZoneRef:
    name: example
  rrdatasRefs:
  - kind: ComputeAddress
    name: app1-app
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: app1-app
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  addressType: EXTERNAL
  description: a test global address
  location: global
  ipVersion: IPV4
