apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: the-namespace/the-map
  name: the-map
  namespace: the-namespace
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|the-namespace|the-map'
data:
  some-key: some-value
---
apiVersion: v1
kind: Pod
metadata: # kpt-merge: the-namespace/the-pod
  name: the-pod
  namespace: the-namespace
  annotations:
    internal.kpt.dev/upstream-identifier: '|Pod|the-namespace|the-pod'
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command:
        - /bin/sh
        - -c
        - env
      env:
        - name: SOME_KEY
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: some-key
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: the-namespace/the-service
  name: the-service
  namespace: the-namespace
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|the-namespace|the-service'
spec:
  ports:
    - name: etcd-server-ssl
      port: 2380
    - name: etcd-client-ssl
      port: 2379
  clusterIP: None
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /old-name
  name: old-name
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|old-name'
---
apiVersion: dev.example.com/v1
kind: MyResource
metadata: # kpt-merge: the-namespace/the-cr
  name: the-cr
  namespace: the-namespace
  annotations:
    internal.kpt.dev/upstream-identifier: 'dev.example.com|MyResource|the-namespace|the-cr'
spec:
  name: foo
