apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: update-dns
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      name: wildcard
      kind: DNSRecordSet
    fieldPaths:
    - spec.rrdatasRefs.[kind=ComputeAddress].name
    options:
      delimiter: '-'
      index: 0
  - select:
      kind: ComputeAddress
    fieldPaths:
    - metadata.name
    #    options:
    #      delimiter: '.'
    #      index: 0
    options:
      delimiter: '-'
      index: 0
